### ISSUE TITLE
Github rate limit via web interface

### ISSUE THREAD

**Issue by richfitz** [r-universe-org/bugs#105]
See attached image, on visiting a universe page I see a github rate limit warning. I have no idea how one might trigger this, or how to set a token that the web browser sees (and I imagine that many users will not have a token set in any case)

![image](https://user-images.githubusercontent.com/1558093/141821356-ca6bfb11-113e-41f9-9577-e1aa30d0ca10.png)

**Comment by jeroen** [comment]
Thanks. I didn't notice this because I guess my browser is always logged in on GitHub.com.

**Comment by jeroen** [comment]
Should be live now, can you let me know if it happens again?

**Comment by richfitz** [comment]
Sure, will do. My browser was also logged in to github, so a bit puzzled as to what caused it really. I can look in the logs if I see it again though
