### ISSUE TITLE
Timeout error on upload

### ISSUE THREAD

**Issue by richfitz** [r-universe-org/bugs#106]
The deployment stage of mrc-ide/dust is now failing regularly due to a timeout: https://github.com/r-universe/mrc-ide/runs/4213387040?check_suite_focus=true

```
  Deploying: dust_0.11.11.tar.gz with md5: 4d49441cdf12d6af2d2099536f6bf3db
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  
    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 137.184.22.243:443...
  * TCP_NODELAY set
  
    0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
...
    0     0    0     0    0     0      0      0 --:--:--  0:00:57 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:58 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0* Connection timed out after 60001 milliseconds
  
    0     0    0     0    0     0      0      0 --:--:--  0:01:00 --:--:--     0
  * Closing connection 3
  curl: (28) Connection timed out after 60001 milliseconds
```

The package binaries are fairly large now (c++ templates smh) perhaps the timeout just needs increasing? It might not be that of course but seeing other builds pass

**Comment by jeroen** [comment]
Thanks. This sometimes randomly happens and I haven't been able to figure out why. It could just be a networking problem with GHA, but maybe there is something up with my server. 

Anyway I triggered a rebuild and then it was fine.

The max size of uploads is set to 100mb so that shouldn't be the issue here.

**Comment by richfitz** [comment]
thanks, must be a coincidence :)

**Comment by jeroen** [comment]
I've done a server upgrade and fixed a database bug, and haven't seen this since. Hopefully it is gone :) 
If you notice this again, please let me know !

**Comment by jeroen** [comment]
OK I'm on to something: https://github.com/r-universe-org/bugs/issues/110
