### ISSUE TITLE
Additional repositories are ignored

### ISSUE THREAD

**Issue by ThierryO** [r-universe-org/bugs#109]
I got this [build error](https://github.com/r-universe/inbo/runs/4369200115?check_suite_focus=true) due to a package (`codemetar`) not available. However the package is available via the [`Additional_repositories`](https://ropensci.r-universe.dev/) listed in the `DESCRIPTION` file.

**Comment by jeroen** [comment]
`install.packages()` does not actually honor `Additional_repositories`. The best solution is to add codemetar to your universe, either by adding it in your registry file, or as a `Remotes:` in your package DESCRIPTION.

**Comment by ThierryO** [comment]
Thanks for the fast reply. I've added `codemetar` to our universe. I assume the `checklist` package will rebuild automatically?

**Comment by jeroen** [comment]
How/where did you add codemetar? I am not seeing it yet.

**Comment by ThierryO** [comment]
I've add it to the same universe as `checklist` https://github.com/inbo/universe/commit/a098eedeab4a464a70f33c58e44a4954374ab867
https://inbo.r-universe.dev/ui#builds contains `codemetar`

The latest version of `checklist` is build now. Hence the workaround of adding the package to the universe works.
