### ISSUE TITLE
Support ssh git remotes

### ISSUE THREAD

**Issue by jeroen** [r-universe-org/bugs#111]
For example: https://github.com/r-universe/r-simmer has some repos with submodules with ssh remotes.

**Comment by jeroen** [comment]
Added a dummykey in https://github.com/r-universe-org/build-source/tree/master/dummykey

**Comment by jeroen** [comment]
Fixed but only for `github.com` remotes because we need to pre-approve the host key: https://github.com/r-universe-org/build-source/commit/e7b20f743f335fa23abfccec85a6c4ea80b618a0

Perhaps a better solution would be to ignore the host keys all together in this step, such that we can clone from non-github ssh remotes as well.

**Comment by Enchufa2** [comment]
Thanks!
