### ISSUE TITLE
cmake on MacOS

### ISSUE THREAD

**Issue by shikokuchuo** [r-universe-org/bugs#121]
Hi Jeroen, I uploaded a new package 'nanonext' that wraps the C library 'libnng'. It requires either the library itself or 'cmake' to build it from source.

The configure script is adapted from your own 'Anticonf' - but if a system installation is not detected it will download and attempt to build the library from source.

The MacOS build currently fails on R-universe as I am guessing there is no 'cmake' installed . If there is, please let me know if there is a better way of detecting cmake - configure already looks for the usual mac location if cmake is not on the $PATH, which seems to work for R-hub's MacOS High Sierra (CRAN's setup).

Otherwise, would be grateful if one of 'libnng' (Homebrew package 'nng') or 'cmake' is installed on the Mac setup. Thanks!

**Comment by jeroen** [comment]
Thank you for the suggestion. I have added cmake to the build image for macos. I think your package should work now.

**Comment by shikokuchuo** [comment]
Seems to have done the trick. Thanks for the super fast response!

**Comment by jeroen** [comment]
Which repository was nanotext in again?

**Comment by jeroen** [comment]
I've triggered an extra scrape run for you so the package should be there in a few minutes...
