### ISSUE TITLE
Release vs dev versions

### ISSUE THREAD

**Issue by pat-s** [r-universe-org/bugs#36]
Hi Jeroen

Thanks for all these efforts here - following the development with great excitement.

Currently R-universe builds binaries/sources for the latest git revision with the version found in DESCRIPTION.

Are there plans for publishing a similar universe for "stable" / "releases" versions only?

**Comment by jeroen** [comment]
We might do something based on git tags at some point, but for now, we consider your default git branch the stable branch.

**Comment by dpprdan** [comment]
Based on [today's rOpenSci commcall](https://ropensci.org/commcalls/may2021-r-universe/), you could also specify the "release" branch in the packages.json file (instead of using the default branch on GitHub).

**Comment by jeroen** [comment]
See https://github.com/r-universe-org/bugs/issues/55

You can now add `{"branch" : "*release"}` to your registry entries, in order to track the latest github release (same syntax as in the `remotes` package).

Does that work for you?
