### ISSUE TITLE
Opt-out feature?

### ISSUE THREAD

**Issue by eddelbuettel** [r-universe-org/bugs#38]
Could you support an option to unlist repos, orgs, or maintainers from r-universe?

**Comment by jeroen** [comment]
The goal is eventually to give the owner of the universe full control over which packages to include via a registry file. But during this pilot we just include existing CRAN/BIOC packages. It will get there.

**Comment by jeroen** [comment]
If you want you can create a registry repository called `universe` in this format: https://github.com/ncov-ic/universe and then I can switch you over

**Comment by eddelbuettel** [comment]
Nice.  Under any 'org' or 'user' as long it is called 'universe', i.e. 'eddelbuettel/universe'?  I can do that, I already scripted some JSON this week :)    

Thanks for the follow-up.

**Comment by jeroen** [comment]
Yes for `https://eddelbuettel.r-universe.dev` it has to be `eddelbuettel/universe`

**Comment by eddelbuettel** [comment]
For completeness, with a universe repository and `packages.json` there, explicitly deleting a package does indeed remove it from this r-universe (and e.g. in my case does not attempt needless builds on unmatching architectures guaranteed to fail).
