### ISSUE TITLE
Would it be possible for devs to configure R-universe to build the 'latest' tagged Github release?

### ISSUE THREAD

**Issue by MilesMcBain** [r-universe-org/bugs#55]
If I am not mistaken, all the builds on universe atm are just the latest repo version which includes dev versions (.9000) suffix.

It would be cool if as a user I could elect to only install versions that have GitHub releases, the equivalent of say: `remotes::install_github("anthonynorth/rdeck@*release")`

Since most devs tag a release when accepted to CRAN, it would allow us to use universes as a CRAN substitute and make ourselves more robust to CRAN irrationality, for example in the case of `{targets}`, which is currently archived.

**Comment by MilesMcBain** [comment]
This was answered in a community call: https://docs.google.com/document/d/1p5laoD-E7MlHFwp84_tgNYYgL6q0ZXlmjK2VsoB0lbE/edit#heading=h.xiqdo4ak8lpd

At present we can configure a tag as our 'branch' but this does not allow us to use the `@*release` magic.

**Comment by jeroen** [comment]
Update: I have added support for the `"branch": "*release"` in the same magic as remotes. Can you test if this works for you?
