### ISSUE TITLE
Something wrong with the RStudio universe

### ISSUE THREAD

**Issue by MilesMcBain** [r-universe-org/bugs#58]
I had trouble installing some but not all RStudio packages yesterday and today.

```
curl https://rstudio.r-universe.dev/bin/windows/contrib/4.0/bookdown_0.22.2.zip
<!DOCTYPE html><html><head><title></title><link rel="stylesheet" href="/assets/css/style.css"></head><body><h1>Package not found</h1><h2>404</h2><pre>NotFoundError: Package not found
    at /node_modules/cranlike/routes/repos.js:165:9
    at runMicrotasks (&lt;anonymous&gt;)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)</pre></body></html>
```

Looking at the build pipeline it seems that it's caused by failure to 'set upstream commit status': https://github.com/r-universe/rstudio/runs/2661612300?check_suite_focus=true 

another example in `htmltools`: https://github.com/r-universe/rstudio/actions/runs/861550535

**Comment by MilesMcBain** [comment]
Note that these packages carry the green 'successful build' icons for windows and macOS in the universe dashboard.

**Comment by jeroen** [comment]
This works for me:

```r
install.packages('bookdown', repos = 'https://rstudio.r-universe.dev')
```

Looks like the bookdown package was updated from 0.22.2 to 0.22.3?

**Comment by jeroen** [comment]
The commit status error is not critical, it just means that we weren't able to add a green checkmark to the upstream R package repository, because they haven't given the app permission to do so. 

But the deployment to R-universe was successful, hence it is green.

**Comment by MilesMcBain** [comment]
Ah thanks for looking into it. That command works for me also. 

I was using `pak` which still fails for me:

```
> pak::pkg_install("bookdown")
v Loading global cached package metadata ... done

> Will update 1 package.
> Will download 1 package with unknown size.
+ bookdown 0.22 > 0.22.2 [dl]
? Do you want to continue (Y/n) Y
i Getting 1 pkg with unknown size
x Failed to download bookdown 0.22.2 (windows)
x Failed to download 1 package.
Error: Failed to download bookdown from `https://rstudio.r-universe.dev/bin/windows/contrib/4.0/bookdown_0.22.2.zip`.
Type .Last.error.trace to see where the error occured
> install.packages('bookdown', repos = 'https://rstudio.r-universe.dev')
Installing package into 'C:/Users/msmcbain/libs/R'
(as 'lib' is unspecified)
trying URL 'https://rstudio.r-universe.dev/bin/windows/contrib/4.0/bookdown_0.22.3.zip'
Content type 'application/zip' length 1093613 bytes (1.0 MB)
downloaded 1.0 MB

package 'bookdown' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\msmcbain\AppData\Local\Temp\Rtmp8uLg0e\downloaded_packages
```

It seems that `pak` is still looking for the `0.22.2` zip file. I'll raise this over on their repo.

**Comment by jeroen** [comment]
Ah okay, I think I know what is going on. Pak is doing some caching and maybe the cache was outdated.

**Comment by jeroen** [comment]
This is due to https://github.com/r-universe-org/bugs/issues/22
I'll temporarily disable caching of PACKAGES files until this is fixed.
