### ISSUE TITLE
ERROR: could not find function "as.person"

### ISSUE THREAD

**Issue by rstub** [r-universe-org/bugs#59]
I tried to add a new non-CRAN package to my universe. However, I get the error message:

```
Adding new package 'RcppArrayFire' from: https://github.com/daqana/rcpparrayfire
Cloning into '/tmp/RtmpChCAma/rstub-universe/RcppArrayFire'...
Updating package 'RcppArrayFire' from: https://github.com/daqana/rcpparrayfire
No packages to delete. Everything is up-to-date

ERROR updating RcppArrayFire from https://github.com/daqana/rcpparrayfire (could not find function "as.person")

Error in sync::sync_from_registry("https://github.com/r-universe/rstub") : 
  Failed to update packages: RcppArrayFire
Execution halted
```
https://github.com/r-universe/rstub/runs/2695611208?check_suite_focus=true

Anything I can do to make this work?

**Comment by jeroen** [comment]
You shouldn't put `as.person` in your DESCRIPTION file: https://github.com/daqana/rcpparrayfire/blob/master/DESCRIPTION#L5-L8

Just use `person()` like here: https://github.com/jeroen/curl/blob/master/DESCRIPTION#L5-L10

**Comment by rstub** [comment]
Thanks!
