### ISSUE TITLE
Print results of testthat output in post-check

### ISSUE THREAD

**Issue by zkamvar** [r-universe-org/bugs#65]
In our universe, one of our packages fails in checks that normally succeed on our own builds. Unfortunately, the R CMD Check output only gives the last 13 lines of test output, which is not enough to determine the source of the error. I have proposed printing the output of testthat checks, which I believe could also be extended to RUnit or tinytest

https://github.com/r-universe-org/post-check/pull/1

**Comment by zkamvar** [comment]
Related discussion: https://discuss.ropensci.org/t/feature-request-add-test-output-to-postcheck/2489

**Comment by jeroen** [comment]
Thank you for the suggestion. I have updated the post-check script to print all the `*.out` and `*.Rout` files.

**Comment by zkamvar** [comment]
Unfortunately, this still skips the testthat failure output (`testthat.Rout.fail)`. I've added https://github.com/r-universe-org/post-check/pull/3 that should address this.
