### ISSUE TITLE
Persistent macOS build failure when package builds for macOS on CRAN

### ISSUE THREAD

**Issue by eddelbuettel** [r-universe-org/bugs#73]
When you have a moment could you look into why `littler` bombs?

At your end, recent build from today:  https://github.com/r-universe/eddelbuettel/actions/runs/1016489225

At CRAN, three happy macOS builds:  https://cran.r-project.org/web/checks/check_results_littler.html

**Comment by jeroen** [comment]
It looks like littler assumes pcre2 is pre-installed on the server, which is not the case currently. I'll try to add that for you.

**Comment by eddelbuettel** [comment]
The autoconf setup is old, and asks R to tell it how it was configured. I think this suggests pre2 is used when R itself is built, but only a run-time is found.   Add the headers would be nice, so thanks.

**Comment by jeroen** [comment]
OK, fix deployed.

**Comment by eddelbuettel** [comment]
Looks much better now, thanks again. I think we have one or two more Heisenbugs left in your setup where it falls behind what CRAN can clearly build from the same sources but I can just file tickets one by one on that.

**Comment by jeroen** [comment]
The problem with rcppziggurat will be resolved by https://github.com/eddelbuettel/rcppziggurat/pull/16. Afaict, the other failures are real issues with the source code.

**Comment by eddelbuettel** [comment]
They could of course be "real issues with the source code" -- can look at them one by one.  The RcppZiggurat one is still 'odd' as you basically demand a new setup when the one CRAN uses has been fine.  But in the grand scheme the winlibs scheme is fine too so I should make to adapt this for RcppZiggurat.

**Comment by eddelbuettel** [comment]
Thanks for the RcppZiggurat reminder. That too is taken care of and working there now -- and giving UCRT to boot on the next upload.
