### ISSUE TITLE
Feature request: minor: custom badge colours

### ISSUE THREAD

**Issue by shikokuchuo** [r-universe-org/bugs#87]
It would be nice to be able to set the colour of the generated r-universe badge like https://www.r-pkg.org/badges/ does with CRAN badges by specifying the query 'color' to the API endpoint. A very low priority ask! Thanks.

**Comment by jeroen** [comment]
You can now pass some of the [badgen parameters](https://github.com/badgen/badgen#usage) such as:

https://jeroen.r-universe.dev/badges/curl?color=pink
https://jeroen.r-universe.dev/badges/curl?style=flat
https://jeroen.r-universe.dev/badges/curl?scale=10

**Comment by shikokuchuo** [comment]
Awesome! Great job on the whole thing as well. Thanks!

**Comment by shikokuchuo** [comment]
https://shikokuchuo.net/ichimoku/ - rather subtle but I think much more visually pleasing.
