### ISSUE TITLE
Update submodules action: Error updating repo - Failed to find git reference for non default branch

### ISSUE THREAD

**Issue by wkmor1** [r-universe-org/bugs#93]
Tried to add a [package](https://github.com/luomus/finbif) from our org to r-universe using it's non-default branch "dev" ([package.json here](https://github.com/luomus/universe/blob/main/packages.json)) but am getting the following error in the actions workflow 
[`ERROR updating finbif from https://github.com/luomus/finbif (Failed to find git reference 'dev')`](https://github.com/r-universe/luomus/runs/3494326750)

Narrowed the issue to something happening around here https://github.com/r-universe-org/sync/blob/72026f704a608f1172b4ff564927f61272235593/R/monorepos.R#L205
but am not sure what exactly is wrong? Have I got the `package.json` specified correctly?

**Comment by jeroen** [comment]
Hmm thanks for reporting. I'll look into it.

**Comment by jeroen** [comment]
I have added a [fix](https://github.com/r-universe-org/sync/commit/7666191fe674f475fda6a5220d2801336b71d604), but I still don't understand why this doesn't seem to be happening for other packages that specify a branch.

**Comment by wkmor1** [comment]
Oh great! Our package is showing up on our universe now. Thanks. Perhaps it had something to do with me adding the package as a non-default branch from the first deploy? I am planning to add a couple of other packages from their dev branches soon. I’ll add one as dev straight away and one without a branch specified until after the first deploy and see how that goes.

**Comment by jeroen** [comment]
OK thanks for helping me test it. Let me know if you run into any additional problems :)
