### ISSUE TITLE
Build fails because latest version of dependency not available in the build

### ISSUE THREAD

**Issue by ThierryO** [r-universe-org/bugs#94]
Our package needs a very recent version of bookdown. That version was published two days ago. The build uses the previous version and hence [fails](https://github.com/r-universe/inbo/runs/3514001825?check_suite_focus=true).

- How do I trigger a rebuild? 
- Shouldn't the build update the dependencies before building the package?

**Comment by jeroen** [comment]
I think this happens because we use the RSPM binaries on Linux, which may lag a few days behind.

**Comment by jeroen** [comment]
Your particular package is fixed now. Moving the discussion to https://github.com/r-universe-org/bugs/issues/95

**Comment by jeroen** [comment]
There is an experimental API and UI now for triggering rebuilds. You can click the circular arrow on https://inbo.r-universe.dev/
